export const GET_HOTELS_REQ = "GET_HOTELS_REQ";
export const GET_HOTELS_SUCCESS = "GET_HOTELS_SUCCESS";
export const GET_HOTELS_FAIL = "GET_HOTELS_FAIL";


export const UPDATE_HOTELS_REQ = "UPDATE_HOTELS_REQ";
export const UPDATE_HOTELS_SUCCESS = "UPDATE_HOTELS_SUCCESS";
export const UPDATE_HOTELS_FAIL = "UPDATE_HOTELS_FAIL";


export const DELETE_HOTELS_REQ = "DELETE_HOTELS_REQ";
export const DELETE_HOTELS_SUCCESS = "DELETE_HOTELS_SUCCESS";
export const DELETE_HOTELS_FAIL = "DELETE_HOTELS_FAIL";